Imports R_Adapter2.R_Adapter.ScriptBuilder

Public Class SummariesSelector
    Inherits MultiElementControl


    Private count As New CheckboxSelector()
    Private Proportion As New CheckboxSelector()
    Private Percentile As New CheckboxSelector()
    Private TrimmedMean As New CheckboxSelector()
    Private NTotal As New CheckboxSelector()
    Private NonMissing As New CheckboxSelector()
    Private NMissing As New CheckboxSelector()
    Private Mean As New CheckboxSelector()
    Private Minimum As New CheckboxSelector()
    Private Mode As New CheckboxSelector()
    Private Maximum As New CheckboxSelector()
    Private kMedian As New CheckboxSelector()
    Private StdDev As New CheckboxSelector()
    Private Variance As New CheckboxSelector()
    Private Range As New CheckboxSelector()
    Private Sum As New CheckboxSelector()
    Private P10 As New CheckboxSelector()
    Private P20 As New CheckboxSelector()
    Private P25 As New CheckboxSelector()
    Private P30 As New CheckboxSelector()
    Private P33 As New CheckboxSelector()
    Private P40 As New CheckboxSelector()
    Private P60 As New CheckboxSelector()
    Private P67 As New CheckboxSelector()
    Private P70 As New CheckboxSelector()
    Private P75 As New CheckboxSelector()
    Private P80 As New CheckboxSelector()
    Private P90 As New CheckboxSelector()
    Private MedianAbsoluteDeviation As New CheckboxSelector()
    Private Kurtosis As New CheckboxSelector()
    Private CoefficientOfVariation As New CheckboxSelector()
    Private Skewness As New CheckboxSelector()
    Private ChkMc As New CheckboxSelector()
    Private ChkQn As New CheckboxSelector()
    Private ChkSn As New CheckboxSelector()
    Private Correlations As New CheckboxSelector()
    Private Covariance As New CheckboxSelector()
    Private First As New CheckboxSelector()
    Private Last As New CheckboxSelector()
    Private nth As New CheckboxSelector()
    Private n_distinct As New CheckboxSelector()
    Private StandardErrorOfMean As New CheckboxSelector()
    Private CircMean As New CheckboxSelector()
    Private CircMedian As New CheckboxSelector()
    Private Min As New CheckboxSelector()
    Private ChkMedianH As New CheckboxSelector()
    Private ChkMax As New CheckboxSelector()
    Private ChkQ1 As New CheckboxSelector()
    Private ChkQ3 As New CheckboxSelector()
    Private ChkQuantile As New CheckboxSelector()
    Private Sd As New CheckboxSelector()
    Private Var As New CheckboxSelector()
    Private AngVar As New CheckboxSelector()
    Private AngDev As New CheckboxSelector()
    Private rho As New CheckboxSelector()
    Private CircRange As New CheckboxSelector()
    Private CoefDetermination As New CheckboxSelector()
    Private CoefPersistence As New CheckboxSelector()
    Private IndexOfAgreement As New CheckboxSelector()
    Private KlingGuptaEfficiency As New CheckboxSelector()
    Private MeanAbsoluteError As New CheckboxSelector()
    Private ModifiedIndexOfAgreement As New CheckboxSelector()
    Private MeanError As New CheckboxSelector()
    Private ModNashSutcliffeEff As New CheckboxSelector()
    Private MeanSquaredError As New CheckboxSelector()
    Private NormRootMeanSquaredError As New CheckboxSelector()
    Private NashSutcliffeEfficiency As New CheckboxSelector()
    Private PercentBias As New CheckboxSelector()
    Private RelativeIndexOfAgreement As New CheckboxSelector()
    Private RootMeanSquaredError As New CheckboxSelector()
    Private RelativeNashSutcliffeEff As New CheckboxSelector()
    Private RatioOfStandardDeviation As New CheckboxSelector()
    Private RatioOfRootMeanSquaredError As New CheckboxSelector()
    Private SumOfSquaredResiduals As New CheckboxSelector()
    Private VolumetricEfficiency As New CheckboxSelector()
    Private Sample As New CheckboxSelector

    Private list As New CheckboxListSelector

    Private SomeotherControl As TextSelector
    Private Sub CreateCheckboxListControls()
        Dim test = list.addCheckbox
        SomeotherControl.LinkVisiblityToControl(test)
    End Sub
End Class
